### ISSUE TITLE
Pooling.cpp changes causes windows builds to fail downstream in iree-org/iree

### ISSUE THREAD

**Issue by renxida** [llvm/torch-mlir#4085]
Recent changes causes windows (and only windows) builds to fail downstream in `iree`. See logs at: https://github.com/iree-org/iree/actions/runs/13757267783/job/38466645214#step:14:10632

I think it has something to do with
- #4035 

# Why I think this is caused by a torch-mlir change

I am specifically seeing these errors:
```
D:\a\iree\iree\c\third_party\torch-mlir\lib\Conversion\TorchToLinalg\Pooling.cpp(1098): error C2131: expression did not evaluate to a constant
D:\a\iree\iree\c\third_party\torch-mlir\lib\Conversion\TorchToLinalg\Pooling.cpp(1099): error C2039: 'getDivisorOverride': is not a member of 'mlir::torch::Torch::AtenAvgPool1dOp'
```

Windows builds were succeeding up to 0307 but failed for 0308, 0309, 0310.

Timeframe lines up with a recent torch-mlir bump in iree.

# Why I think this is caused by #4035

The error message mentions Pooling.cpp in TorchToLinalg

**Comment by ScottTodd** [comment]
Fix is up for review at https://github.com/llvm/torch-mlir/pull/4086.

I can repro this in my local (downstream) IREE build. I _can't_ repro this on the same system yet in torch-mlir standalone. Checking how the compiler flags differ between projects.
