### PR TITLE
g++ build fix

### PR DESCRIPTION
**Pull request by newling**
Introduced in 704cfdaf0893fa4078ab744a915a56367282dcaa of @wu-s-john 

g++ compiler error: 

Pooling.cpp:177:13: error: explicit specialization in non-namespace scope ‘class 

Design looks good, g++ is just freaking out for no good reason. Un-nesting the template classes fixes the error. 

We don't have g++ CI. This hopefully happens infrequently enough that we can just fix manually. My service to those folks who really like building with g++... :)

### CODE REVIEW

**Comment by stellaraccident** [comment]
Thanks!

**Review by stellaraccident — APPROVED** [review]
