### PR TITLE
[Bazel] Check cache directory exists before changing owners

### PR DESCRIPTION
**Pull request by sjain-stanford**
This fixes a seeding issue with the [previous PR](https://github.com/llvm/torch-mlir/pull/1240) where bazel build's GHA cache is not present to begin with and one of the commands (chown) fails on it. Should get the Bazel build back to green.

### CODE REVIEW

**Review by silvasean — APPROVED** [review]

**Comment by sjain-stanford** [comment]
Co-incidentally, there's another failure after the rebase to `develop` (after [this commit](https://github.com/llvm/torch-mlir/commit/57681f794764a34c34e2be7f07f7dfbcafa683c1)):
```
bazel-out/k8-fastbuild/bin/external/torch-mlir/_objs/TorchMLIRTorchPasses/Passes.pic.o:Passes.cpp:function (anonymous namespace)::registerLowerToBackendContractPass()::{lambda()#1}::operator()() const: error: undefined reference to 'mlir::torch::Torch::createLowerToBackendContractPass(int, bool)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Let me land this now, and send a follow-on PR to include `"lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp",` to the `TorchMLIRTorchPasses` target.
